import { StyleSheet, Dimensions } from "react-native";

const DEVICE_WIDTH = Dimensions.get('window').width;

const home = StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundImage: {
    flex: 1,
    resizeMode: "cover",
    justifyContent: "center",
    zIndex: -1,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(32, 21, 60, 0.5)",
  },
  content: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  title: {
    marginTop: 55,
    fontSize: 58,
    fontWeight: "bold",
    color: "#FFF",
    letterSpacing: -2.2,
  },
  securityFeedContainer: {
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 40,
    backgroundColor: "rgba(141, 135, 147, 0.3)",
    padding: 15,
    borderRadius: 10,
    elevation: 14,
  },
  securityFeedTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFF',
    marginBottom: 10, 
  },
  securityFeed: {
    width: DEVICE_WIDTH - 80,
    height: (DEVICE_WIDTH - 20) * (4/6),
    backgroundColor: 'black',
  },
  carousel: {
    flexDirection: 'row',
    marginBottom: 20,
    width: 200,
  },
  deviceCard: {
    width: DEVICE_WIDTH - 285,
    height: (DEVICE_WIDTH - 4) * (2/6),
    backgroundColor: '#A4AE9E',
    borderColor: "white",
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10,
    elevation: 5,
  },
  deviceName: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  deviceState: {
    fontSize: 16,
    marginBottom: 10,
  },
  carouselContainer: {
    flexDirection: 'row',
    paddingHorizontal: 10,
    marginBottom: 20,
    alignItems: 'center',
  },
  carouselArrow: {
    marginHorizontal: 10,
  },
  deviceControls:{
    flexDirection: 'row',
    marginTop: 10,
  },
  button: {
    backgroundColor: '#6C63FF',
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginHorizontal: 5,
    marginBottom: 20,
    marginRight: 5,
    elevation: 3, 
    shadowColor: '#000', 
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  buttonText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  buttonCamera:{
    backgroundColor: '#6C63FF',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 7,
    marginHorizontal: 5,
    marginBottom: 5,
    marginRight: 5,
    marginTop: 12,
    elevation: 3, 
    shadowColor: '#000', 
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  buttonCameraText:{
    textAlign: 'center',
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  buttonOn: {
    backgroundColor: '#6C63FF',
    borderRadius: 20,
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginHorizontal: 5,
    marginBottom: 20,
    marginRight: 10,
    elevation: 3, 
    shadowColor: '#ffff', 
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  buttonOff: {
    backgroundColor: '#6C63FF',
    borderRadius: 20,
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginHorizontal: 5,
    marginBottom: 20,
    elevation: 3, 
    shadowColor: '#000', 
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  image: {
        width: 300,
        height: 300,
      },
  alertContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    padding: 20,
    justifyContent: 'center',
   alignItems: 'center',
    },
  alertText: {
    color: 'white',
    fontSize: 16,
    textAlign: 'center',
    },
});

export default home;
